export const BUTTONS = [
  {
    pressFunction: "7",
    textStyle: "text-h2",
    BGColor: "bg-theme1-button",
    shadowColor: "light",
    hoverColor: "white",
    doubleWidth: false,
  },
  {
    pressFunction: "8",
    textStyle: "text-h2",
    BGColor: "bg-theme1-button",
    shadowColor: "light",
    hoverColor: "white",
    doubleWidth: false,
  },
  {
    pressFunction: "9",
    textStyle: "text-h2",
    BGColor: "bg-theme1-button",
    shadowColor: "light",
    hoverColor: "white",
    doubleWidth: false,
  },
  {
    pressFunction: "DEL",
    textStyle: "text-reset text-theme1-numbers",
    BGColor: "bg-theme1-resetdel",
    shadowColor: "dark",
    hoverColor: "dark",
    doubleWidth: false,
  },
  {
    pressFunction: "4",
    textStyle: "text-h2",
    BGColor: "bg-theme1-button",
    shadowColor: "light",
    hoverColor: "white",
    doubleWidth: false,
  },
  {
    pressFunction: "5",
    textStyle: "text-h2",
    BGColor: "bg-theme1-button",
    shadowColor: "light",
    hoverColor: "white",
    doubleWidth: false,
  },
  {
    pressFunction: "6",
    textStyle: "text-h2",
    BGColor: "bg-theme1-button",
    shadowColor: "light",
    hoverColor: "white",
    doubleWidth: false,
  },
  {
    pressFunction: "+",
    textStyle: "text-h2",
    BGColor: "bg-theme1-button",
    shadowColor: "light",
    hoverColor: "white",
    doubleWidth: false,
  },
  {
    pressFunction: "1",
    textStyle: "text-h2",
    BGColor: "bg-theme1-button",
    shadowColor: "light",
    hoverColor: "white",
    doubleWidth: false,
  },
  {
    pressFunction: "2",
    textStyle: "text-h2",
    BGColor: "bg-theme1-button",
    shadowColor: "light",
    hoverColor: "white",
    doubleWidth: false,
  },
  {
    pressFunction: "3",
    textStyle: "text-h2",
    BGColor: "bg-theme1-button",
    shadowColor: "light",
    hoverColor: "white",
    doubleWidth: false,
  },
  {
    pressFunction: "-",
    textStyle: "text-h2",
    BGColor: "bg-theme1-button",
    shadowColor: "light",
    hoverColor: "white",
    doubleWidth: false,
  },
  {
    pressFunction: ".",
    textStyle: "text-h2",
    BGColor: "bg-theme1-button",
    shadowColor: "light",
    hoverColor: "white",
    doubleWidth: false,
  },
  {
    pressFunction: "0",
    textStyle: "text-h2",
    BGColor: "bg-theme1-button",
    shadowColor: "light",
    hoverColor: "white",
    doubleWidth: false,
  },
  {
    pressFunction: "/",
    textStyle: "text-h2",
    BGColor: "bg-theme1-button",
    shadowColor: "light",
    hoverColor: "white",
    doubleWidth: false,
  },
  {
    pressFunction: "x",
    textStyle: "text-h2",
    BGColor: "bg-theme1-button",
    shadowColor: "light",
    hoverColor: "white",
    doubleWidth: false,
  },
  {
    pressFunction: "RESET",
    textStyle: "text-reset text-theme1-numbers",
    BGColor: "bg-theme1-resetdel",
    shadowColor: "dark",
    hoverColor: "dark",
    doubleWidth: true,
  },
  {
    pressFunction: "=",
    textStyle: "text-reset text-theme1-numbers",
    BGColor: "bg-theme1-gleich",
    shadowColor: "red",
    hoverColor: "red",
    doubleWidth: true,
  },
];
